import type { Metadata } from 'next'
import { Inter, Roboto } from 'next/font/google'
import '@/styles/reset.css'
import { PropsWithChildren } from 'react'
import StyledComponentsRegistry from '@/lib/registry'
import ThemeClient from '@/providers/ThemeProvider'
import { ShoppingCarContextProvider } from '@/contexts/ShoppingCartContext/ShoppingCartContext'
import { GlobalSpinnerContextProvider } from '@/contexts/GlobalSpinnerActionsContext'
import GlobalSpinner from '@/components/organisms/Spinners/GlobalSpinner'
import { BreadcrumbContextProvider } from '@/contexts/BreadcrumbContext'
// import SWRClient from '@/providers/SwrProvider'

// フォントをロード（可変フォントを使用）
const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-roboto',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="ja">
      <body className={`${inter.variable} ${roboto.variable}`}>
        <StyledComponentsRegistry>
          <ThemeClient>
            {/* NOTE: SWRの設定
                  使用しないが設定方法例として残している
              */}
            {/* <SWRClient> */}
            <GlobalSpinnerContextProvider>
              <ShoppingCarContextProvider>
                <BreadcrumbContextProvider>
                  <GlobalSpinner />
                  {children}
                </BreadcrumbContextProvider>
              </ShoppingCarContextProvider>
            </GlobalSpinnerContextProvider>
            {/* </SWRClient> */}
          </ThemeClient>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
