version: "3.8"
services:
  app:
    container_name: shop-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - "3000:3000"
      - "6006:6006"
      - "5555:5555"
      - "8000:8000"
    stdin_open: true
    tty: true
